services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    jhg\ElternsprechtagBundle\Controller\:
        resource: '../../Controller/*'
        public: true
        tags: ['controller.service_arguments']

    jhg\ElternsprechtagBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Resources}/*'

    jhg\ElternsprechtagBundle\EventListener\MenuListener:
        tags:
            - { name: kernel.event_listener, event: iserv_portal.menu_main, method: onBuildMainMenu }
            # - { name: kernel.event_listener, event: iserv_portal.menu_admin, method: onBuildAdminMenu }